
OrdererOrgs:
  - Name: OrdererOrg
    Domain: private.net
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org0
    Domain: org0.private.net

    Template:
      Count: 1

    Users:
      Count: 1

  - Name: Org1
    Domain: org1.private.net

    Template:
      Count: 1

    Users:
      Count: 1
