version: '2'

x-common:
  core-loglevel: &core-loglevel
    CORE_LOGGING_PEER=DEBUG

  chaincode-loglevel: &chaincode-loglevel
    CORE_CHAINCODE_LOGGING_LEVEL=DEBUG

  state-database: &state-database
    CORE_LEDGER_STATE_STATEDATABASE=LevelDB
    
services:
  base-peer:
    image: hyperledger/fabric-peer
    environment:
      - *core-loglevel
      - *chaincode-loglevel
      - *state-database
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_privatenet
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    volumes:
      - /var/run/:/host/var/run/
      - ./config:/etc/hyperledger/configtx
    networks:
      - privatenet
